//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caykimnho_studio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Detail
    {
        public int ID { get; set; }
        public int ID_Cart { get; set; }
        public int ID_Products { get; set; }
        public string Product_Images { get; set; }
        public string Product_Name { get; set; }
        public string Product_Color { get; set; }
        public string Product_Size { get; set; }
        public int Product_Quantity { get; set; }
        public decimal Product_Price { get; set; }
        public decimal Product_Import_Price { get; set; }
        public decimal Product_Sale { get; set; }
        public System.DateTime Add_Date { get; set; }
        public int ID_Color { get; set; }
        public int ID_Size { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Products Products { get; set; }
        public virtual Size Size { get; set; }
    }
}
