//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caykimnho_studio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailProducts
    {
        public int ID { get; set; }
        public int ID_Products { get; set; }
        public int ID_Colors { get; set; }
        public int ID_Size { get; set; }
        public decimal Import_Price { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Images { get; set; }
        public decimal Sale { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Products Products { get; set; }
        public virtual Size Size { get; set; }
    }
}
