//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caykimnho_studio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Cart_Detail = new HashSet<Cart_Detail>();
            this.DetailProducts = new HashSet<DetailProducts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool State { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Videos { get; set; }
        public string Images { get; set; }
        public int ToTalViews { get; set; }
        public int TotalOrders { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Detail> Cart_Detail { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailProducts> DetailProducts { get; set; }
    }
}
